services:
  hlds:
    build:
      context: .
      args:
        - GAME=${GAME}
        - FLAGS=${FLAGS}
    volumes:
      - "./config:/temp/config"
      - "./mods:/temp/mods"
    ports:
      - "27015:27015/udp"
      - "27015:27015"
      - "26900:2690/udp"
    environment:
      - GAME=${GAME}
      - FLAGS=${FLAGS}
    command: +maxplayers 12 +log on
