name: Bug Report 🐝
description: Found an issue? Report it here!
title: "bug 🐝: "
labels: ["bug 🐝", "triage ⚠️"]
assignees:
  - JamesIves
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report.
        Please provide as much detail as possible to help us fix the issue.

        Please consider checking [the Valve Developer Wiki](https://developer.valvesoftware.com/wiki/Half-Life_Dedicated_Server) for additional information on server startup commands and configuration files before submitting a bug report as your issue may be related to a misconfiguration as opposed to a bug with the Docker script.
  - type: textarea
    id: what-happened
    attributes:
      label: What happened?
      description: Tell us what you see and what you expected to see.
    validations:
      required: true
  - type: dropdown
    id: approach
    attributes:
      label: Approach
      description: How are you running the container image?
      options:
        - I am using a pre-built image on Dockerhub (jives/hlds)
        - I am using a pre-built image on the GitHub Container Registry (ghcr.io/jamesives/hlds)
        - I built the image myself
      default: 0
    validations:
      required: true
  - type: dropdown
    id: game
    attributes:
      label: What game are you trying to run?
      multiple: true
      options:
        - Half-Life Deathmatch (valve)
        - Half-Life Opposing Force (gearbox)
        - Counter-Strike (cstrike)
        - Counter-Strike Condition Zero (czero)
        - Day of Defeat (dod)
        - Team Fortress Classic (tfc)
        - Deathmatch Classic (dmc)
        - Ricochet (ricochet)
        - Custom Mod
  - type: textarea
    id: logs
    attributes:
      label: Docker Logs
      description: Please copy and paste your Docker logs. This will be automatically formatted into code, so no need for backticks.
      render: shell
  - type: textarea
    id: compose
    attributes:
      label: Startup Setup
      description: Please copy and paste the command you are using to start the container, or your docker-compose file.
      render: yml
